name: softban
version: '1.0-SNAPSHOT'
main: org.avarion.softban.Softban
api-version: '1.18'

commands:
  softban:
    aliases:
      - sb
    description: soft ban someone
    usage: /softban <set|remove> <playername> [1-5]
    permission: softban.admin
